import jsPDF from 'jspdf'

class BookPDFGenerator {
  constructor() {
    this.pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    })
    this.pageWidth = this.pdf.internal.pageSize.getWidth()
    this.pageHeight = this.pdf.internal.pageSize.getHeight()
    this.margin = 20
    this.currentY = this.margin
    this.lineHeight = 7
    this.pageNumber = 1
  }

  reset() {
    this.pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    })
    this.currentY = this.margin
    this.pageNumber = 1
  }

  addNewPage() {
    this.pdf.addPage()
    this.pageNumber++
    this.currentY = this.margin
  }

  checkPageBreak(heightNeeded = 10) {
    if (this.currentY + heightNeeded > this.pageHeight - this.margin) {
      this.addNewPage()
    }
  }

  // Page 1: Title Page
  addTitlePage(title) {
    this.pdf.setFont('times', 'bold')
    this.pdf.setFontSize(32)
    
    // Calculate center position
    const titleLines = this.pdf.splitTextToSize(title, this.pageWidth - 2 * this.margin)
    const titleHeight = titleLines.length * 15
    const startY = (this.pageHeight - titleHeight) / 2
    
    // Draw title centered
    titleLines.forEach((line, index) => {
      const textWidth = this.pdf.getTextWidth(line)
      const x = (this.pageWidth - textWidth) / 2
      this.pdf.text(line, x, startY + (index * 15))
    })
    
    // Add decorative line
    const lineY = startY + titleHeight + 20
    this.pdf.setLineWidth(0.5)
    this.pdf.line(this.pageWidth / 4, lineY, 3 * this.pageWidth / 4, lineY)
    
    // Add "Generated by AI Book Generator" at bottom
    this.pdf.setFontSize(10)
    this.pdf.setFont('times', 'italic')
    const footer = 'Generated by AI Book Generator'
    const footerWidth = this.pdf.getTextWidth(footer)
    this.pdf.text(footer, (this.pageWidth - footerWidth) / 2, this.pageHeight - 20)
    
    // Add date
    this.pdf.setFontSize(8)
    const date = new Date().toLocaleDateString()
    const dateWidth = this.pdf.getTextWidth(date)
    this.pdf.text(date, (this.pageWidth - dateWidth) / 2, this.pageHeight - 15)
  }

  // Page 2: Table of Contents / Outline
  addTableOfContents(chapters) {
    this.addNewPage()
    
    this.pdf.setFont('times', 'bold')
    this.pdf.setFontSize(24)
    this.pdf.text('Table of Contents', this.margin, this.currentY)
    
    this.currentY += 15
    this.pdf.setLineWidth(0.3)
    this.pdf.line(this.margin, this.currentY, this.pageWidth - this.margin, this.currentY)
    this.currentY += 10
    
    this.pdf.setFont('times', 'normal')
    this.pdf.setFontSize(12)
    
    let chapterStartPage = 3
    chapters.forEach((chapter, index) => {
      this.checkPageBreak(15)
      
      // Chapter number and title
      const chapterText = `Chapter ${chapter.number}: ${chapter.title}`
      const pageNumText = `${chapterStartPage}`
      
      // Draw chapter name
      this.pdf.text(chapterText, this.margin, this.currentY)
      
      // Draw page number (right-aligned)
      const pageNumWidth = this.pdf.getTextWidth(pageNumText)
      this.pdf.text(pageNumText, this.pageWidth - this.margin - pageNumWidth, this.currentY)
      
      // Draw dotted line between
      const textWidth = this.pdf.getTextWidth(chapterText)
      const dotsStart = this.margin + textWidth + 2
      const dotsEnd = this.pageWidth - this.margin - pageNumWidth - 2
      const dotSpacing = 3
      
      this.pdf.setFont('times', 'normal')
      for (let x = dotsStart; x < dotsEnd; x += dotSpacing) {
        this.pdf.text('.', x, this.currentY)
      }
      
      this.currentY += this.lineHeight + 3
      
      // Estimate pages per chapter (rough estimate: 1 page per 2000 characters)
      if (chapter.content) {
        const estimatedPages = Math.ceil(chapter.content.length / 2000)
        chapterStartPage += estimatedPages
      } else {
        chapterStartPage += 1
      }
    })
  }

  // Add chapter content
  addChapter(chapterNumber, chapterTitle, content) {
    this.addNewPage()
    
    // Chapter heading
    this.pdf.setFont('times', 'bold')
    this.pdf.setFontSize(20)
    const heading = `Chapter ${chapterNumber}`
    this.pdf.text(heading, this.margin, this.currentY)
    this.currentY += 10
    
    // Chapter title
    this.pdf.setFontSize(18)
    const titleLines = this.pdf.splitTextToSize(chapterTitle, this.pageWidth - 2 * this.margin)
    titleLines.forEach(line => {
      this.pdf.text(line, this.margin, this.currentY)
      this.currentY += 8
    })
    
    this.currentY += 5
    
    // Decorative line
    this.pdf.setLineWidth(0.3)
    this.pdf.line(this.margin, this.currentY, this.pageWidth - this.margin, this.currentY)
    this.currentY += 10
    
    // Chapter content
    this.pdf.setFont('times', 'normal')
    this.pdf.setFontSize(11)
    
    // Clean content - remove markdown headers
    let cleanContent = content
      .replace(/^#\s+Chapter\s+\d+:.*$/gm, '') // Remove chapter headers
      .replace(/^#+\s+/gm, '') // Remove other markdown headers
      .trim()
    
    // Split into paragraphs
    const paragraphs = cleanContent.split('\n\n')
    
    paragraphs.forEach(paragraph => {
      if (paragraph.trim()) {
        this.checkPageBreak(20)
        
        const lines = this.pdf.splitTextToSize(
          paragraph.trim(),
          this.pageWidth - 2 * this.margin
        )
        
        lines.forEach(line => {
          this.checkPageBreak()
          this.pdf.text(line, this.margin, this.currentY)
          this.currentY += this.lineHeight
        })
        
        this.currentY += 3 // Paragraph spacing
      }
    })
  }

  // Generate complete PDF
  generatePDF(title, chapters) {
    this.reset()
    
    // Page 1: Title
    if (title) {
      this.addTitlePage(title)
    }
    
    // Page 2: Table of Contents (only if we have chapter titles)
    const chaptersWithTitles = chapters.filter(ch => ch.title)
    if (chaptersWithTitles.length > 0) {
      this.addTableOfContents(chaptersWithTitles)
    }
    
    // Page 3+: Chapters with content
    chapters.forEach(chapter => {
      if (chapter.content) {
        this.addChapter(chapter.number, chapter.title, chapter.content)
      }
    })
    
    return this.pdf
  }

  // Get PDF as blob for preview
  getBlob() {
    return this.pdf.output('blob')
  }

  // Get PDF as data URL for preview
  getDataUrl() {
    return this.pdf.output('dataurlstring')
  }

  // Download PDF
  download(filename) {
    this.pdf.save(filename)
  }

  // Get total pages
  getPageCount() {
    return this.pdf.internal.getNumberOfPages()
  }
}

export default BookPDFGenerator
